# These are supported funding model platforms

# GitHub Sponsors - enable at https://github.com/sponsors
github: [codenzia]

# Buy Me a Coffee: https://www.buymeacoffee.com
# buy_me_a_coffee: your_username

# Ko-fi: https://ko-fi.com
# ko_fi: your_username

# Open Collective: https://opencollective.com
# open_collective: your_collective

# Patreon: https://www.patreon.com
# patreon: your_username

# Liberapay: https://liberapay.com
# liberapay: your_username

# Thanks.dev: https://thanks.dev
# thanks_dev: your_username
